version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phishguard-backend
    ports:
      - '3001:3001'
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - SALT_ROUNDS=${SALT_ROUNDS}
      - API_URL=${API_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
    networks:
      - phishguard-network
    volumes:
      - .:/app

  redis:
    image: 'redis:alpine'
    container_name: phishguard-redis
    ports:
      - '6379:6379'
    networks:
      - phishguard-network

networks:
  phishguard-network:
    driver: bridge
